// import { StyleSheet } from "react-native";
// import { THEME } from "../../../theme";

// export const hiveDetailsStyles = StyleSheet.create({
//   centerState: {
//     flex: 1,
//     alignItems: "center",
//     justifyContent: "center",
//     gap: 12,
//     padding: 24,
//   },
//   stateText: {
//     color: THEME.textMuted,
//     fontWeight: "600",
//     fontSize: 14,
//   },
//   errorTitle: {
//     fontSize: 16,
//     fontWeight: "800",
//     color: THEME.primary,
//   },
//   errorBody: {
//     color: "#B91C1C",
//     fontSize: 13,
//     fontWeight: "600",
//     textAlign: "center",
//   },
//   primaryButtonSmall: {
//     marginTop: 12,
//     backgroundColor: THEME.accent,
//     borderRadius: 10,
//     paddingVertical: 10,
//     paddingHorizontal: 16,
//     alignItems: "center",
//     justifyContent: "center",
//     alignSelf: "center",
//   },
//   primaryButtonText: {
//     color: THEME.primary,
//     fontWeight: "800",
//     fontSize: 15,
//   },
//   detailPage: {
//     paddingHorizontal: 14,
//     paddingTop: 14,
//     paddingBottom: 32,
//   },
//   detailHeroCard: {
//     backgroundColor: THEME.primary,
//     borderRadius: 16,
//     padding: 18,
//     marginBottom: 14,
//   },
//   detailHeroTopRow: {
//     flexDirection: "row",
//     alignItems: "center",
//     gap: 12,
//   },
//   detailHeroTextWrap: { flex: 1 },
//   detailHiveName: {
//     fontSize: 20,
//     fontWeight: "800",
//     color: "#FFFFFF",
//     marginBottom: 3,
//   },
//   detailHeroMetaRow: {
//     flexDirection: "row",
//     alignItems: "center",
//     gap: 3,
//   },
//   detailHeroMeta: {
//     fontSize: 12,
//     color: "rgba(255,255,255,0.6)",
//     fontWeight: "500",
//   },
//   detailStateDurationRow: {
//     flexDirection: "row",
//     alignItems: "center",
//     justifyContent: "space-between",
//     gap: 10,
//     marginTop: 10,
//   },
//   detailStateLabelContainer: {
//     flex: 1,
//   },
//   detailStateLabel: {
//     fontSize: 15,
//     fontWeight: "800",
//   },
//   detailLastAnalysisTime: {
//     fontSize: 11,
//     color: "rgba(255,255,255,0.6)",
//     fontWeight: "500",
//     marginTop: 2,
//   },
//   detailDurationBadge: {
//     flexDirection: "row",
//     alignItems: "center",
//     gap: 3,
//     backgroundColor: "rgba(255,255,255,0.15)",
//     paddingHorizontal: 8,
//     paddingVertical: 3,
//     borderRadius: 20,
//   },
//   detailDurationText: {
//     fontSize: 11,
//     color: "rgba(255,255,255,0.8)",
//     fontWeight: "600",
//   },
//   heroDivider: {
//     height: 1,
//     backgroundColor: "rgba(255,255,255,0.12)",
//     marginVertical: 14,
//   },
//   detailAlertBanner: {
//     flexDirection: "row",
//     alignItems: "flex-start",
//     gap: 10,
//     backgroundColor: "rgba(255,178,104,0.12)",
//     borderRadius: 10,
//     padding: 12,
//   },
//   detailAlertIconWrap: {
//     width: 32,
//     height: 32,
//     borderRadius: 8,
//     backgroundColor: "rgba(255,178,104,0.2)",
//     alignItems: "center",
//     justifyContent: "center",
//   },
//   detailAlertTitle: {
//     color: THEME.accent,
//     fontSize: 13,
//     fontWeight: "800",
//     marginBottom: 3,
//   },
//   detailAlertSubtitle: {
//     color: "rgba(255,255,255,0.7)",
//     fontSize: 12,
//     lineHeight: 17,
//   },
//   statusPill: {
//     borderRadius: 999,
//     paddingHorizontal: 12,
//     paddingVertical: 8,
//   },
//   statusPillText: {
//     fontSize: 12,
//     fontWeight: "800",
//   },
//   card: {
//     backgroundColor: "#FFFFFF",
//     borderWidth: 1,
//     borderColor: THEME.line,
//     borderRadius: 14,
//     padding: 14,
//     marginBottom: 14,
//   },
//   cardTitle: {
//     fontSize: 15,
//     fontWeight: "800",
//     color: THEME.primary,
//     marginBottom: 2,
//   },
//   rowBetween: {
//     flexDirection: "row",
//     alignItems: "center",
//     justifyContent: "space-between",
//   },
//   hiveAlertCountBadge: {
//     backgroundColor: THEME.surfaceSoft,
//     borderRadius: 999,
//     paddingHorizontal: 10,
//     paddingVertical: 3,
//     borderWidth: 1,
//     borderColor: THEME.line,
//   },
//   hiveAlertCountText: {
//     fontSize: 11,
//     fontWeight: "700",
//     color: THEME.textMuted,
//   },
//   hiveAlertEmpty: {
//     alignItems: "center",
//     paddingVertical: 20,
//     gap: 8,
//   },
//   hiveAlertEmptyText: {
//     fontSize: 13,
//     color: THEME.textMuted,
//     fontWeight: "600",
//   },
//   hiveAlertRow: {
//     flexDirection: "row",
//     borderRadius: 12,
//     borderWidth: 1,
//     borderColor: THEME.line,
//     backgroundColor: "#FFFFFF",
//     marginTop: 10,
//     overflow: "hidden",
//   },
//   hiveAlertSeverityBar: {
//     width: 4,
//     borderTopLeftRadius: 12,
//     borderBottomLeftRadius: 12,
//   },
//   hiveAlertContent: {
//     flex: 1,
//     padding: 12,
//     gap: 6,
//   },
//   hiveAlertHeader: {
//     flexDirection: "row",
//     alignItems: "center",
//     justifyContent: "space-between",
//   },
//   hiveAlertSeverityBadge: {
//     borderRadius: 999,
//     paddingHorizontal: 8,
//     paddingVertical: 3,
//   },
//   hiveAlertSeverityText: {
//     fontSize: 11,
//     fontWeight: "700",
//   },
//   hiveAlertDate: {
//     fontSize: 11,
//     color: THEME.textMuted,
//     fontWeight: "500",
//   },
//   hiveAlertTitle: {
//     fontSize: 13,
//     fontWeight: "700",
//     color: THEME.primary,
//   },
//   hiveAlertSummary: {
//     fontSize: 12,
//     color: THEME.textMuted,
//     lineHeight: 17,
//   },
//   metricsSubtitle: {
//     color: "#667085",
//     fontWeight: "600",
//     fontSize: 12,
//     marginTop: 2,
//     marginBottom: 10,
//   },
//   metricsHighlightsRow: {
//     flexDirection: "row",
//     flexWrap: "nowrap",
//     gap: 8,
//     marginBottom: 10,
//   },
//   metricHighlightCard: {
//     flex: 1,
//     backgroundColor: THEME.surfaceSoft,
//     borderWidth: 1,
//     borderColor: THEME.line,
//     borderRadius: 12,
//     paddingVertical: 12,
//     paddingHorizontal: 12,
//     gap: 4,
//   },
//   metricHighlightLabel: {
//     color: THEME.textMuted,
//     fontSize: 11,
//     fontWeight: "600",
//   },
//   metricHighlightValue: {
//     color: THEME.primary,
//     fontSize: 20,
//     fontWeight: "800",
//   },
//   metricsLegendRow: {
//     flexDirection: "row",
//     gap: 14,
//     marginBottom: 8,
//   },
//   metricsLegendItem: {
//     flexDirection: "row",
//     alignItems: "center",
//   },
//   legendDot: {
//     width: 10,
//     height: 10,
//     borderRadius: 10,
//     marginRight: 8,
//   },
//   legendText: {
//     color: "#475467",
//     fontWeight: "600",
//   },
//   weatherHeader: {
//     flexDirection: "row",
//     alignItems: "center",
//     gap: 8,
//     marginBottom: 4,
//   },
//   weatherSubtitle: {
//     color: "#667085",
//     fontWeight: "600",
//     fontSize: 12,
//     marginBottom: 14,
//   },
//   weatherDataRow: {
//     flexDirection: "row",
//     gap: 12,
//     marginBottom: 10,
//   },
//   weatherCard: {
//     flex: 1,
//     borderRadius: 12,
//     paddingVertical: 16,
//     paddingHorizontal: 14,
//     alignItems: "center",
//     gap: 6,
//     borderWidth: 1,
//     borderColor: THEME.line,
//   },
//   weatherValue: {
//     color: THEME.primary,
//     fontSize: 22,
//     fontWeight: "800",
//   },
//   weatherLabel: {
//     color: THEME.textMuted,
//     fontSize: 11,
//     fontWeight: "600",
//   },
//   weatherTimestamp: {
//     fontSize: 11,
//     color: THEME.textMuted,
//     fontWeight: "500",
//     textAlign: "center",
//   },
// });

import { StyleSheet } from "react-native";
import { THEME } from "../../../theme";

type ThemeSnapshot = typeof THEME;

export function createHiveDetailsStyles(t: ThemeSnapshot) {
  return StyleSheet.create({
  centerState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 24,
  },
  stateText: {
    color: t.textMuted,
    fontWeight: "600",
    fontSize: 14,
  },
  errorTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: t.primary,
  },
  errorBody: {
    color: "#B91C1C",
    fontSize: 13,
    fontWeight: "600",
    textAlign: "center",
  },
  primaryButtonSmall: {
    marginTop: 12,
    backgroundColor: t.accent,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  primaryButtonText: {
    color: t.primary,
    fontWeight: "800",
    fontSize: 15,
  },
  detailPage: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 32,
  },
  detailHeroCard: {
    backgroundColor: t.primary,
    borderRadius: 16,
    padding: 18,
    marginBottom: 14,
  },
  detailHeroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  detailHeroTextWrap: { flex: 1 },
  detailHiveName: {
    fontSize: 20,
    fontWeight: "800",
    color: t.surface,
    marginBottom: 3,
  },
  detailHeroMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  detailHeroMeta: {
    fontSize: 12,
    color: "rgba(255,255,255,0.6)",
    fontWeight: "500",
  },
  detailStateDurationRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 10,
  },
  detailStateLabelContainer: {
    flex: 1,
  },
  detailStateLabel: {
    fontSize: 15,
    fontWeight: "800",
  },
  detailLastAnalysisTime: {
    fontSize: 11,
    color: t.textMuted,
    fontWeight: "500",
    marginTop: 2,
  },
  detailDurationBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "rgba(255,255,255,0.15)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
  },
  detailDurationText: {
    fontSize: 11,
    color: "rgba(255,255,255,0.8)",
    fontWeight: "600",
  },
  heroDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.12)",
    marginVertical: 14,
  },
  detailAlertBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: "rgba(255,178,104,0.12)",
    borderRadius: 10,
    padding: 12,
  },
  detailAlertIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "rgba(255,178,104,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  detailAlertTitle: {
    color: t.accent,
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 3,
  },
  detailAlertSubtitle: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 12,
    lineHeight: 17,
  },
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  statusPillText: {
    fontSize: 12,
    fontWeight: "800",
  },
card: {
    backgroundColor: t.surface,
    borderWidth: 1,
    borderColor: t.line,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: t.primary,
    marginBottom: 2,
  },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  hiveAlertCountBadge: {
    backgroundColor: "#DC2626",
    borderRadius: 999,
    minWidth: 22,
    height: 22,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  hiveAlertCountText: {
    fontSize: 11,
    fontWeight: "800",
    color: t.surface,
  },
  hiveAlertEmpty: {
    alignItems: "center",
    paddingVertical: 24,
    gap: 6,
  },
  hiveAlertEmptyText: {
    fontSize: 13,
    color: "#16A34A",
    fontWeight: "700",
  },
  hiveAlertRow: {
    flexDirection: "row",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: t.line,
    backgroundColor: t.surface,
    marginTop: 10,
    overflow: "hidden",
  },
  hiveAlertSeverityBar: {
    width: 4,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
  },
  hiveAlertContent: {
    flex: 1,
    padding: 12,
    gap: 6,
  },
  hiveAlertHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  hiveAlertSeverityBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  hiveAlertSeverityText: {
    fontSize: 11,
    fontWeight: "700",
  },
  hiveAlertDate: {
    fontSize: 11,
    color: t.textMuted,
    fontWeight: "500",
  },
  hiveAlertTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: t.primary,
  },
  hiveAlertSummary: {
    fontSize: 12,
    color: t.textMuted,
    lineHeight: 17,
  },
  // Compact Alert Styles
  hiveAlertRowCompact: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: t.surfaceSoft,
    borderWidth: 1,
    borderColor: t.line,
    marginTop: 8,
  },
  alertIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  alertContentCompact: {
    flex: 1,
    gap: 2,
  },
  alertTitleCompact: {
    fontSize: 13,
    fontWeight: "700",
    color: t.primary,
  },
  alertTimeCompact: {
    fontSize: 11,
    color: t.textMuted,
    fontWeight: "500",
  },
  metricsSubtitle: {
    color: t.textMuted,
    fontWeight: "600",
    fontSize: 12,
    marginTop: 2,
    marginBottom: 10,
  },
  metricsHighlightsRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 8,
    marginBottom: 10,
  },
  metricHighlightCard: {
    flex: 1,
    backgroundColor: t.surfaceSoft,
    borderWidth: 1,
    borderColor: t.line,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    gap: 4,
  },
  metricHighlightLabel: {
    color: t.textMuted,
    fontSize: 11,
    fontWeight: "600",
  },
  metricHighlightValue: {
    color: t.primary,
    fontSize: 20,
    fontWeight: "800",
  },
  metricsLegendRow: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 8,
  },
  metricsLegendItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 10,
    marginRight: 8,
  },
  legendText: {
    color: t.textMuted,
    fontWeight: "600",
  },
  weatherHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  weatherSubtitle: {
    color: t.textMuted,
    fontWeight: "600",
    fontSize: 12,
    marginBottom: 14,
  },
  weatherDataRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 10,
  },
  weatherCard: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 14,
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: t.line,
  },
  weatherValue: {
    color: t.primary,
    fontSize: 22,
    fontWeight: "800",
  },
  weatherLabel: {
    color: t.textMuted,
    fontSize: 11,
    fontWeight: "600",
  },
  weatherTimestamp: {
    fontSize: 11,
    color: t.textMuted,
    fontWeight: "500",
    textAlign: "center",
  },
  deleteButton: {
    backgroundColor: "#DC2626",
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  deleteButtonDisabled: {
    opacity: 0.5,
  },
  deleteButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
  },
  deleteWarning: {
    fontSize: 11,
    color: t.textMuted,
    textAlign: "center",
    marginTop: 8,
    fontWeight: "500",
  },
  // Delete Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContainer: {
    backgroundColor: t.surface,
    borderRadius: 16,
    width: "100%",
    maxWidth: 400,
    overflow: "hidden",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  modalHeader: {
    alignItems: "center",
    paddingTop: 24,
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  modalIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#FEE2E2",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: t.primary,
  },
  modalBody: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    gap: 12,
  },
  modalMessage: {
    fontSize: 15,
    color: t.textMuted,
    textAlign: "center",
    lineHeight: 22,
  },
  modalHiveName: {
    fontWeight: "800",
    color: t.primary,
  },
  modalWarningBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: "#FEF2F2",
    borderLeftWidth: 3,
    borderLeftColor: "#DC2626",
    borderRadius: 8,
    padding: 12,
  },
  modalWarningText: {
    flex: 1,
    fontSize: 12,
    color: "#B91C1C",
    fontWeight: "600",
    lineHeight: 18,
  },
  modalErrorBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FEE2E2",
    borderRadius: 8,
    padding: 12,
  },
  modalErrorText: {
    flex: 1,
    fontSize: 12,
    color: "#DC2626",
    fontWeight: "600",
  },
  modalFooter: {
    flexDirection: "row",
    gap: 12,
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: t.line,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  modalCancelButton: {
    backgroundColor: t.surfaceSoft,
    borderWidth: 1,
    borderColor: t.line,
  },
  modalCancelButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: t.primary,
  },
  modalDeleteButton: {
    backgroundColor: "#DC2626",
    flexDirection: "row",
    gap: 6,
  },
  modalDeleteButtonDisabled: {
    opacity: 0.5,
  },
  modalDeleteButtonText: {
    fontSize: 15,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  });
}

export const hiveDetailsStyles = createHiveDetailsStyles(THEME);