import { StyleSheet } from "react-native";
import { THEME } from "../../theme";

type ThemeSnapshot = typeof THEME;

export function createProfileStyles(t: ThemeSnapshot) {
  return StyleSheet.create({
  centerState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 24,
  },
  stateText: {
    color: t.textMuted,
    fontWeight: "600",
    fontSize: 14,
  },
  profilePage: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 32,
    gap: 12,
  },
profileHeroCard: {
    backgroundColor: t.surface,
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: t.line,
    gap: 8,
  },
  profileAvatarCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: t.primary,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  profileAvatarInitials: {
    color: t.accent,
    fontSize: 26,
    fontWeight: "800",
  },
  profileHeroName: {
    fontSize: 20,
    fontWeight: "800",
    color: t.primary,
  },
  profileHeroRole: {
    fontSize: 13,
    color: t.textMuted,
    fontWeight: "600",
  },
  profileNameInput: {
    fontSize: 18,
    fontWeight: "700",
    color: t.primary,
    borderBottomWidth: 2,
    borderBottomColor: t.accent,
    paddingBottom: 4,
    textAlign: "center",
    width: "100%",
  },
profileSection: {
    backgroundColor: t.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: t.line,
    padding: 14,
  },
  profileSectionTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: t.primary,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 12,
  },
  profileFieldRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 4,
  },
  profileFieldIcon: {
    marginTop: 2,
  },
  profileFieldLabel: {
    fontSize: 11,
    color: t.textMuted,
    fontWeight: "600",
    marginBottom: 2,
  },
  profileFieldValue: {
    fontSize: 14,
    color: t.primary,
    fontWeight: "600",
  },
  profileFieldInput: {
    fontSize: 14,
    color: t.primary,
    borderBottomWidth: 1,
    borderBottomColor: t.line,
    paddingVertical: 4,
  },
  profileDivider: {
    height: 1,
    backgroundColor: t.line,
    marginVertical: 10,
  },
  profileActionsRow: {
    flexDirection: "row",
    gap: 10,
  },
profileSecondaryBtn: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: t.line,
    backgroundColor: t.surface,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  profileEditBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: t.line,
    backgroundColor: t.surface,
    paddingVertical: 12,
  },
  profileSecondaryBtnText: {
    color: t.text,
    fontWeight: "700",
    fontSize: 13,
  },
  profilePrimaryBtn: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: t.accent,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  profilePrimaryBtnText: {
    color: t.primary,
    fontWeight: "800",
    fontSize: 13,
  },
  profileEditBtnText: {
    color: t.primary,
    fontWeight: "700",
    fontSize: 13,
  },
  profileLinkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
  },
  profileLinkText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: t.primary,
  },
  profileLogoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#FEE2E2",
    backgroundColor: t.surface,
    paddingVertical: 13,
  },
  profileLogoutText: {
    color: "#B42318",
    fontWeight: "700",
    fontSize: 14,
  },
  profileVersion: {
    textAlign: "center",
    fontSize: 12,
    color: t.textMuted,
    fontWeight: "500",
    marginTop: 4,
  },
  pwModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  pwModalCard: {
    backgroundColor: t.surface,
    borderRadius: 16,
    padding: 20,
    width: "100%",
    maxWidth: 340,
    gap: 14,
  },
  pwModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  pwModalTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: t.text,
  },
  pwModalCloseBtn: {
    padding: 4,
  },
  pwModalField: {
    gap: 6,
  },
  pwModalLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: t.textMuted,
  },
  pwModalInputRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: t.line,
    borderRadius: 10,
    backgroundColor: t.surface,
    paddingHorizontal: 12,
    paddingRight: 8,
  },
  pwModalInput: {
    flex: 1,
    paddingVertical: 10,
    fontSize: 14,
    color: t.text,
  },
  pwModalError: {
    color: "#DC2626",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 4,
  },
  pwModalActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  pwModalCancelBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: t.line,
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: t.surface,
  },
  pwModalCancelText: {
    fontSize: 13,
    fontWeight: "700",
    color: t.text,
  },
  pwModalSaveBtn: {
    flex: 1,
    backgroundColor: t.accent,
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  pwModalSaveText: {
    fontSize: 13,
    fontWeight: "800",
    color: t.primary,
  },
  });
}

export const profileStyles = createProfileStyles(THEME);