import { StyleSheet } from "react-native";
import { THEME } from "../../theme";

export const loginStyles = StyleSheet.create({
  authShell: {
    flex: 1,
    backgroundColor: THEME.primary,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    overflow: "hidden",
  },
  backgroundOrbOne: {
    position: "absolute",
    top: -40,
    left: -60,
    width: 220,
    height: 220,
    borderRadius: 220,
    backgroundColor: "rgba(255, 178, 104, 0.12)",
  },
  backgroundOrbTwo: {
    position: "absolute",
    bottom: 80,
    right: -56,
    width: 200,
    height: 200,
    borderRadius: 200,
    backgroundColor: "rgba(255, 178, 104, 0.08)",
  },
  formCard: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingVertical: 28,
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  brandMark: {
    alignSelf: "center",
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: THEME.primary,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    borderWidth: 2,
    borderColor: THEME.accent,
  },
  brandLogo: {
    width: 40,
    height: 40,
    tintColor: THEME.accent,
  },
  brandText: {
    textAlign: "center",
    color: THEME.primary,
    fontWeight: "800",
    letterSpacing: 0.8,
    marginBottom: 20,
  },
  heading: {
    textAlign: "center",
    fontSize: 24,
    fontWeight: "800",
    color: "#27272A",
    marginBottom: 20,
  },
  input: {
    width: "100%",
    borderWidth: 1,
    borderColor: THEME.line,
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 14,
    color: "#101828",
    backgroundColor: "#FFFFFF",
    marginBottom: 4,
  },
  inputError: {
    borderColor: "#DC2626",
    marginBottom: 2,
  },
  fieldError: {
    width: "100%",
    fontSize: 12,
    color: "#DC2626",
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  errorBox: {
    backgroundColor: "#FEF2F2",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#FCA5A5",
    padding: 10,
    marginBottom: 10,
  },
  errorBody: {
    color: "#B91C1C",
    fontSize: 13,
    fontWeight: "600",
  },
  primaryButton: {
    backgroundColor: THEME.accent,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  primaryButtonWide: {
    marginTop: 6,
  },
  primaryButtonText: {
    color: THEME.primary,
    fontWeight: "800",
    fontSize: 15,
  },
  pressed: {
    opacity: 0.86,
    transform: [{ scale: 0.99 }],
  },
  separatorRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 16,
  },
  separatorLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E2E8F0",
  },
  separatorText: {
    marginHorizontal: 12,
    color: "#A0A8B6",
    fontWeight: "600",
  },
  authTextPrompt: {
    textAlign: "center",
    color: "#667085",
  },
  linkAction: {
    textAlign: "center",
    color: THEME.primary,
    fontWeight: "700",
    marginTop: 4,
  },
});
