"""
HTTP API connector for remote farmer audio sources.

This connector replaces SSH/SFTP with HTTP API calls to the farmer's
external data source server. The farmer provides:
  - Base URL (e.g., https://abc123.ngrok-free.dev)
  - API Key (UUID generated by the farmer's server)

The poller calls list_recordings() to discover new files and
download_file_bytes() to fetch audio data for processing.
"""

from typing import Optional
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
import socket
import logging

logger = logging.getLogger("bsads.http_connector")


def _translate_localhost_url(url: str) -> str:
    """
    Translate host IPs to host.docker.internal when running in Docker.
    
    When the BSADS API container needs to communicate with services on the
    host machine (like a farmer simulation server), Docker networking requires
    using 'host.docker.internal' instead of the host's external IP.
    
    Args:
        url: Original URL (e.g., http://196.43.168.57:8086)
    
    Returns:
        Translated URL if needed (e.g., http://host.docker.internal:8086)
    """
    if not url:
        return url
    
    # Check if we're running inside Docker by looking for /.dockerenv
    import os
    if not os.path.exists('/.dockerenv'):
        return url  # Not in Docker, use URL as-is
    
    try:
        from urllib.parse import urlparse, urlunparse
        parsed = urlparse(url)
        host = parsed.hostname
        
        if not host:
            return url
        
        # Translate localhost/127.0.0.1 to host.docker.internal
        if host in ('localhost', '127.0.0.1', '0.0.0.0'):
            new_host = 'host.docker.internal'
            logger.info(f"🔄 Translating {host} → {new_host} (Docker host gateway)")
            new_netloc = f"{new_host}:{parsed.port}" if parsed.port else new_host
            return urlunparse(parsed._replace(netloc=new_netloc))
        
        # Check if this looks like a host IP on the same machine
        # Common patterns: 192.168.x.x, 10.x.x.x, 172.x.x.x, or public IPs like 196.x.x.x
        # When both API and simulation server are on the same physical machine
        if host.startswith(('192.168.', '10.', '172.16.', '172.17.', '172.18.',
                           '172.19.', '172.20.', '172.21.', '172.22.', '172.23.',
                           '172.24.', '172.25.', '172.26.', '172.27.', '172.28.',
                           '172.29.', '172.30.', '172.31.', '196.', '197.')):
            # Try to detect if we're actually trying to reach the host
            try:
                # Read /etc/hosts to see if we can use host.docker.internal
                with open('/etc/hosts', 'r') as f:
                    if 'host.docker.internal' in f.read():
                        new_host = 'host.docker.internal'
                        logger.info(f"🔄 Translating {host} → {new_host} (same-host detection)")
                        new_netloc = f"{new_host}:{parsed.port}" if parsed.port else new_host
                        return urlunparse(parsed._replace(netloc=new_netloc))
            except Exception as e:
                logger.debug(f"Could not check /etc/hosts: {e}")
        
    except Exception as e:
        logger.warning(f"URL translation failed: {e}")
    
    return url


def _build_session(api_key: str, timeout: int = 30) -> requests.Session:
    """
    Create a requests Session with retry logic and authentication.
    
    Args:
        api_key: The API key provided by the farmer
        timeout: Request timeout in seconds
    
    Returns:
        Configured requests.Session
    """
    session = requests.Session()
    
    # Add API key to all requests
    session.headers.update({"X-API-Key": api_key})
    
    # Configure retry strategy
    retry_strategy = Retry(
        total=3,
        backoff_factor=1,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET", "POST"]
    )
    
    adapter = HTTPAdapter(max_retries=retry_strategy)
    session.mount("http://", adapter)
    session.mount("https://", adapter)
    
    return session


def test_connection(config: dict) -> dict:
    """
    Test the HTTP API connection to the farmer's server.
    
    Args:
        config: Connection config dict with keys:
            - api_base_url: Base URL of the farmer's server
            - api_key: API key for authentication
    
    Returns:
        {"ok": True} or {"ok": False, "error": "<message>"}
    """
    try:
        base_url = config.get("api_base_url", "").rstrip("/")
        base_url = _translate_localhost_url(base_url)  # Translate for Docker
        api_key = config.get("api_key", "")
        
        if not base_url:
            return {"ok": False, "error": "api_base_url is required"}
        if not api_key:
            return {"ok": False, "error": "api_key is required"}
        
        session = _build_session(api_key, timeout=10)
        
        # Test health endpoint
        health_response = session.get(f"{base_url}/health", timeout=10)
        health_response.raise_for_status()
        
        # Test recordings list endpoint (requires auth)
        recordings_response = session.get(f"{base_url}/recordings", timeout=10)
        recordings_response.raise_for_status()
        
        return {"ok": True}
    
    except requests.exceptions.HTTPError as exc:
        if exc.response.status_code == 401:
            return {"ok": False, "error": "Invalid API key (401 Unauthorized)"}
        return {"ok": False, "error": f"HTTP {exc.response.status_code}: {exc}"}
    
    except requests.exceptions.ConnectionError as exc:
        return {"ok": False, "error": f"Connection failed: {exc}"}
    
    except requests.exceptions.Timeout as exc:
        return {"ok": False, "error": f"Request timeout: {exc}"}
    
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def list_recordings(config: dict, hive_id: str = None, hive_name: str = None) -> list[str]:
    """
    List available audio recordings from the farmer's server.
    
    Args:
        config: Connection config dict with keys:
            - api_base_url: Base URL of the farmer's server
            - api_key: API key for authentication
        hive_id: Optional hive ID to filter recordings (deprecated, use hive_name)
        hive_name: Optional hive name to filter recordings for a specific hive
    
    Returns:
        List of recording paths (e.g., ["Hive 22/file1.wav", "Hive 23/file2.wav"])
    
    Raises:
        requests.exceptions.RequestException: On connection or HTTP errors
    """
    base_url = config.get("api_base_url", "").rstrip("/")
    base_url = _translate_localhost_url(base_url)  # Translate for Docker
    api_key = config.get("api_key", "")
    
    if not base_url or not api_key:
        raise ValueError("api_base_url and api_key are required in config")
    
    session = _build_session(api_key)
    
    # Use hive_name if provided, otherwise fall back to hive_id (for backwards compatibility)
    params = {}
    if hive_name:
        params["hive_name"] = hive_name
    elif hive_id:
        params["hive_id"] = hive_id
    
    response = session.get(f"{base_url}/recordings", params=params, timeout=10)
    response.raise_for_status()
    
    data = response.json()
    return data.get("recordings", [])


def download_file_bytes(config: dict, filepath: str) -> bytes:
    """
    Download a single audio file from the farmer's server.
    
    Args:
        config: Connection config dict with keys:
            - api_base_url: Base URL of the farmer's server
            - api_key: API key for authentication
        filepath: Path to the file (e.g., "hive-id/filename.wav")
    
    Returns:
        Audio file contents as bytes
    
    Raises:
        requests.exceptions.RequestException: On connection or HTTP errors
    """
    base_url = config.get("api_base_url", "").rstrip("/")
    base_url = _translate_localhost_url(base_url)  # Translate for Docker
    api_key = config.get("api_key", "")
    
    if not base_url or not api_key:
        raise ValueError("api_base_url and api_key are required in config")
    
    session = _build_session(api_key)
    response = session.get(
        f"{base_url}/recordings/{filepath}",
        timeout=60,  # Longer timeout for file downloads
        stream=True
    )
    response.raise_for_status()
    
    # Read the entire file into memory
    return response.content


def get_recording_url(config: dict, filepath: str) -> str:
    """
    Construct the full URL for a recording file.
    
    This is used as the source_url identifier in AudioSource records.
    
    Args:
        config: Connection config dict with api_base_url
        filepath: Path to the file (e.g., "hive-id/filename.wav")
    
    Returns:
        Full URL to the recording (e.g., "https://server.com/recordings/api-token/hive-id/file.wav")
    """
    base_url = config.get("api_base_url", "").rstrip("/")
    return f"{base_url}/recordings/{filepath}"


def create_hive_folder(config: dict, hive_name: str) -> dict:
    """
    Request the farmer's server to create a hive folder.
    
    This is an optional endpoint - not all farmer servers may implement it.
    Folders can also be created manually by the farmer or auto-created on first upload.
    
    Args:
        config: Connection config dict with keys:
            - api_base_url: Base URL of the farmer's server
            - api_key: API key for authentication
        hive_name: Name of the hive (will be sanitized for filesystem safety)
    
    Returns:
        {"ok": True, "folder": "<folder_name>"} or {"ok": False, "error": "<message>"}
    """
    try:
        base_url = config.get("api_base_url", "").rstrip("/")
        base_url = _translate_localhost_url(base_url)  # Translate for Docker
        api_key = config.get("api_key", "")
        
        if not base_url or not api_key:
            return {"ok": False, "error": "api_base_url and api_key are required"}
        
        session = _build_session(api_key, timeout=10)
        
        # POST /recordings/hives/{hive_name} to create a hive folder
        response = session.post(
            f"{base_url}/recordings/hives/{hive_name}",
            timeout=10
        )
        response.raise_for_status()
        
        return {"ok": True, "folder": hive_name}
    
    except requests.exceptions.HTTPError as exc:
        if exc.response.status_code == 404:
            return {"ok": False, "error": "Endpoint not supported - farmer should create folder manually"}
        if exc.response.status_code == 401:
            return {"ok": False, "error": "Invalid API key (401 Unauthorized)"}
        return {"ok": False, "error": f"HTTP {exc.response.status_code}: {exc}"}
    
    except requests.exceptions.ConnectionError as exc:
        return {"ok": False, "error": f"Connection failed: {exc}"}
    
    except requests.exceptions.Timeout as exc:
        return {"ok": False, "error": f"Request timeout: {exc}"}
    
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def list_conditions(config: dict, hive_name: str) -> list[str]:
    """
    List available CSV condition files from the farmer's server.
    
    Args:
        config: Connection config dict with keys:
            - api_base_url: Base URL of the farmer's server
            - api_key: API key for authentication
        hive_name: Hive name to filter conditions for a specific hive
    
    Returns:
        List of condition file paths (e.g., ["Hive01/data_20260620.csv"])
    
    Raises:
        requests.exceptions.RequestException: On connection or HTTP errors
    """
    base_url = config.get("api_base_url", "").rstrip("/")
    base_url = _translate_localhost_url(base_url)  # Translate for Docker
    api_key = config.get("api_key", "")
    
    if not base_url or not api_key:
        raise ValueError("api_base_url and api_key are required in config")
    
    session = _build_session(api_key)
    
    params = {"hive_name": hive_name} if hive_name else {}
    
    response = session.get(f"{base_url}/conditions", params=params, timeout=10)
    response.raise_for_status()
    
    data = response.json()
    return data.get("conditions", [])


def download_condition_file(config: dict, filepath: str) -> str:
    """
    Download a single CSV condition file from the farmer's server.
    
    Args:
        config: Connection config dict with keys:
            - api_base_url: Base URL of the farmer's server
            - api_key: API key for authentication
        filepath: Path to the file (e.g., "Hive01/data.csv")
    
    Returns:
        CSV file contents as string
    
    Raises:
        requests.exceptions.RequestException: On connection or HTTP errors
    """
    base_url = config.get("api_base_url", "").rstrip("/")
    base_url = _translate_localhost_url(base_url)  # Translate for Docker
    api_key = config.get("api_key", "")
    
    if not base_url or not api_key:
        raise ValueError("api_base_url and api_key are required in config")
    
    session = _build_session(api_key)
    response = session.get(
        f"{base_url}/conditions/{filepath}",
        timeout=30,
        stream=True
    )
    response.raise_for_status()
    
    # Return as text (CSV)
    return response.text


def delete_condition_file(config: dict, filepath: str) -> dict:
    """
    Delete a single CSV condition file from the farmer's server after processing.
    
    Args:
        config: Connection config dict with keys:
            - api_base_url: Base URL of the farmer's server
            - api_key: API key for authentication
        filepath: Path to the file (e.g., "Hive01/data.csv")
    
    Returns:
        {"ok": True, "detail": "..."} or {"ok": False, "error": "<message>"}
    """
    try:
        base_url = config.get("api_base_url", "").rstrip("/")
        base_url = _translate_localhost_url(base_url)  # Translate for Docker
        api_key = config.get("api_key", "")
        
        if not base_url or not api_key:
            return {"ok": False, "error": "api_base_url and api_key are required"}
        
        session = _build_session(api_key, timeout=10)
        response = session.delete(
            f"{base_url}/conditions/{filepath}",
            timeout=10
        )
        response.raise_for_status()
        
        return {"ok": True, "detail": "File deleted successfully"}
    
    except requests.exceptions.HTTPError as exc:
        if exc.response.status_code == 404:
            return {"ok": False, "error": "File not found"}
        if exc.response.status_code == 401:
            return {"ok": False, "error": "Invalid API key (401 Unauthorized)"}
        return {"ok": False, "error": f"HTTP {exc.response.status_code}: {exc}"}
    
    except requests.exceptions.ConnectionError as exc:
        return {"ok": False, "error": f"Connection failed: {exc}"}
    
    except requests.exceptions.Timeout as exc:
        return {"ok": False, "error": f"Request timeout: {exc}"}
    
    except Exception as exc:
        return {"ok": False, "error": str(exc)}
