import { StyleSheet } from "react-native";
import { THEME } from "../../theme";

export const welcomeStyles = StyleSheet.create({
  welcomeShell: {
    flex: 1,
    backgroundColor: THEME.primary,
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 80,
    paddingBottom: 40,
    paddingHorizontal: 24,
    overflow: "hidden",
  },
  backgroundOrbOne: {
    position: "absolute",
    top: -40,
    left: -60,
    width: 220,
    height: 220,
    borderRadius: 220,
    backgroundColor: "rgba(255, 178, 104, 0.12)",
  },
  backgroundOrbTwo: {
    position: "absolute",
    bottom: 80,
    right: -56,
    width: 200,
    height: 200,
    borderRadius: 200,
    backgroundColor: "rgba(255, 178, 104, 0.08)",
  },
  backgroundOrbThree: {
    position: "absolute",
    top: "40%",
    left: "30%",
    width: 120,
    height: 120,
    borderRadius: 120,
    backgroundColor: "rgba(255, 178, 104, 0.06)",
  },
  welcomeLogoWrap: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  welcomeLogoRing: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "rgba(255,178,104,0.15)",
    borderWidth: 2,
    borderColor: "rgba(255,178,104,0.4)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  welcomeLogo: {
    width: 90,
    height: 90,
    tintColor: THEME.accent,
  },
  welcomeAppName: {
    fontSize: 32,
    fontWeight: "800",
    fontFamily: THEME.fontFamily.extraBold,
    color: THEME.accent,
    letterSpacing: 4,
  },
  welcomeAppSub: {
    fontSize: 12,
    color: "rgba(255,178,104,0.7)",
    fontWeight: "600",
    fontFamily: THEME.fontFamily.semiBold,
    letterSpacing: 0.5,
    marginTop: 4,
    textAlign: "center",
  },
  welcomeBottomCard: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 28,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: -4 },
    elevation: 8,
  },
  welcomeHeadline: {
    fontSize: 26,
    fontWeight: "800",
    fontFamily: THEME.fontFamily.extraBold,
    color: THEME.primary,
    textAlign: "center",
    lineHeight: 34,
    marginBottom: 10,
  },
  welcomeSubtitle: {
    fontSize: 13,
    color: THEME.textMuted,
    fontFamily: THEME.fontFamily.regular,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 24,
  },
  welcomePrimaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: THEME.accent,
    borderRadius: 12,
    paddingVertical: 15,
    width: "100%",
    marginBottom: 12,
  },
  welcomePrimaryBtnText: {
    color: THEME.primary,
    fontWeight: "800",
    fontFamily: THEME.fontFamily.extraBold,
    fontSize: 16,
  },
  pressed: {
    opacity: 0.86,
    transform: [{ scale: 0.99 }],
  },
});
