import { StyleSheet } from "react-native";
import { Theme } from "../../../theme";

export const createEditHiveStyles = (theme: Theme) =>
  StyleSheet.create({
    container: { padding: 16, paddingBottom: 40 },
    card: { backgroundColor: theme.surface, borderRadius: 12, padding: 20 },
    cardTitle: {
      fontSize: 22,
      fontWeight: "800",
      color: theme.primary,
      marginBottom: 6,
    },
    cardSubtitle: { fontSize: 14, color: theme.textMuted, marginBottom: 24 },
    formGroup: { marginBottom: 20 },
    label: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.text,
      marginBottom: 8,
    },
    required: { color: "#EF4444" },
    input: {
      backgroundColor: theme.page,
      borderWidth: 1,
      borderColor: theme.line,
      borderRadius: 8,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: theme.text,
    },
    inputDisabled: {
      backgroundColor: "#F3F4F6",
      color: "#9CA3AF",
    },
    inputError: { borderColor: "#EF4444" },
    errorText: { color: "#EF4444", fontSize: 12, marginTop: 4 },
    submitButton: {
      backgroundColor: theme.primary,
      borderRadius: 10,
      paddingVertical: 14,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      marginTop: 8,
    },
    submitButtonDisabled: { opacity: 0.6 },
    submitButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
    cancelButton: {
      backgroundColor: "transparent",
      borderRadius: 10,
      paddingVertical: 14,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 12,
    },
    cancelButtonText: { color: theme.textMuted, fontSize: 15, fontWeight: "600" },
    successModalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.45)",
      alignItems: "center",
      justifyContent: "center",
    },
    successModalBox: {
      width: 300,
      backgroundColor: theme.surface,
      borderRadius: 18,
      padding: 28,
      alignItems: "center" as const,
      shadowColor: "#000",
      shadowOpacity: 0.2,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 10,
    },
    successModalIcon: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: "#DCFCE7",
      alignItems: "center" as const,
      justifyContent: "center" as const,
      marginBottom: 16,
    },
    successModalTitle: {
      fontSize: 18,
      fontWeight: "800" as const,
      color: theme.primary,
      textAlign: "center" as const,
      marginBottom: 8,
    },
    successModalBody: {
      fontSize: 14,
      color: theme.textMuted,
      textAlign: "center" as const,
      lineHeight: 20,
      marginBottom: 22,
    },
    successModalBtn: {
      backgroundColor: theme.accent,
      borderRadius: 10,
      paddingVertical: 12,
      paddingHorizontal: 40,
    },
    successModalBtnText: {
      color: theme.primary,
      fontWeight: "800" as const,
      fontSize: 15,
    },
    locationButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: theme.accent,
      borderRadius: 8,
      paddingVertical: 12,
      marginBottom: 12,
    },
    locationButtonText: {
      color: theme.primary,
      fontSize: 15,
      fontWeight: "700",
    },
    locationButtonDisabled: {
      opacity: 0.6,
    },
    coordinatesRow: {
      flexDirection: "row",
      gap: 10,
    },
    coordinateInput: {
      flex: 1,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
  });
